#!/usr/bin/env bash
# =============================================================================
# setup-solver.sh - Generate solver .env from deployment output
# =============================================================================
# Usage: ./script/setup-solver.sh [CHAIN_ID]
# Default CHAIN_ID: 31337 (Anvil)

set -euo pipefail

CHAIN_ID="${1:-31337}"
DEPLOY_FILE="deployments/${CHAIN_ID}.json"
SOLVER_DIR="solver"
SOLVER_ENV="${SOLVER_DIR}/.env"

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "=== Latch Solver Setup ==="
echo "Chain ID: ${CHAIN_ID}"
echo "Deployment file: ${DEPLOY_FILE}"

# ── 1. Check deployment file exists ─────────────────────────────
if [ ! -f "${DEPLOY_FILE}" ]; then
    echo -e "${RED}Error: ${DEPLOY_FILE} not found.${NC}"
    echo "Run 'make deploy-full-local' first to generate deployment addresses."
    exit 1
fi

# ── 2. Check jq is available ────────────────────────────────────
if ! command -v jq &> /dev/null; then
    echo -e "${RED}Error: jq is required but not installed.${NC}"
    echo "Install with: brew install jq (macOS) or apt install jq (Linux)"
    exit 1
fi

# ── 3. Extract addresses ────────────────────────────────────────
LATCH_HOOK=$(jq -r '.latchHook' "${DEPLOY_FILE}")
POOL_MANAGER=$(jq -r '.poolManager' "${DEPLOY_FILE}")
SOLVER_REWARDS=$(jq -r '.solverRewards' "${DEPLOY_FILE}")
TOKEN0=$(jq -r '.token0 // empty' "${DEPLOY_FILE}")
TOKEN1=$(jq -r '.token1 // empty' "${DEPLOY_FILE}")
POOL_FEE=$(jq -r '.poolFee // "3000"' "${DEPLOY_FILE}")
TICK_SPACING=$(jq -r '.tickSpacing // "60"' "${DEPLOY_FILE}")

# Validate no zero addresses
if [ "${LATCH_HOOK}" = "0x0000000000000000000000000000000000000000" ] || [ -z "${LATCH_HOOK}" ]; then
    echo -e "${RED}Error: Invalid latchHook address in ${DEPLOY_FILE}${NC}"
    exit 1
fi

# ── 4. Determine RPC URL and private key ────────────────────────
if [ "${CHAIN_ID}" = "31337" ]; then
    RPC_URL="http://127.0.0.1:8545"
    # Anvil account #1 (solver account, separate from deployer #0)
    PRIVATE_KEY="0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"
else
    RPC_URL="${RPC_URL:-}"
    PRIVATE_KEY="${SOLVER_PRIVATE_KEY:-}"
    if [ -z "${RPC_URL}" ] || [ -z "${PRIVATE_KEY}" ]; then
        echo -e "${YELLOW}Warning: RPC_URL and SOLVER_PRIVATE_KEY env vars needed for non-local chains.${NC}"
    fi
fi

# ── 5. Compute pool ID (if tokens available) ────────────────────
POOL_ID=""
if [ -n "${TOKEN0}" ] && [ -n "${TOKEN1}" ]; then
    # Pool ID is keccak256(abi.encode(currency0, currency1, fee, tickSpacing, hooks))
    # For local testing we'll leave it for the solver to compute on startup
    POOL_ID="auto"
fi

# ── 6. Check solver directory ───────────────────────────────────
if [ ! -d "${SOLVER_DIR}" ]; then
    echo -e "${RED}Error: ${SOLVER_DIR}/ directory not found.${NC}"
    exit 1
fi

# ── 7. Install solver dependencies ──────────────────────────────
if [ ! -d "${SOLVER_DIR}/node_modules" ]; then
    echo "Installing solver dependencies..."
    (cd "${SOLVER_DIR}" && npm install)
fi

# ── 8. Write solver .env ────────────────────────────────────────
cat > "${SOLVER_ENV}" << EOF
# =============================================================================
# Solver Configuration - Auto-generated by setup-solver.sh
# Chain ID: ${CHAIN_ID}
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# =============================================================================

# RPC
RPC_URL=${RPC_URL}

# Solver private key
PRIVATE_KEY=${PRIVATE_KEY}

# Contract addresses
LATCH_HOOK_ADDRESS=${LATCH_HOOK}
SOLVER_REWARDS_ADDRESS=${SOLVER_REWARDS}

# Pool configuration
POOL_ID=${POOL_ID}
CURRENCY0=${TOKEN0}
CURRENCY1=${TOKEN1}
POOL_FEE=${POOL_FEE}
TICK_SPACING=${TICK_SPACING}

# Circuit directory (relative to solver/)
CIRCUIT_DIR=../circuits

# Polling interval in ms (12s = 1 block on mainnet)
POLL_INTERVAL_MS=1000

# Logging
LOG_LEVEL=debug
EOF

echo ""
echo -e "${GREEN}Solver .env written to: ${SOLVER_ENV}${NC}"
echo ""
echo "Addresses:"
echo "  LatchHook:     ${LATCH_HOOK}"
echo "  SolverRewards: ${SOLVER_REWARDS}"
if [ -n "${TOKEN0}" ]; then
    echo "  Token0:        ${TOKEN0}"
    echo "  Token1:        ${TOKEN1}"
fi
echo ""
echo "To start the solver:"
echo "  cd solver && npm run dev"
echo ""
echo "=== Setup Complete ==="
