#!/usr/bin/env bash
# =============================================================================
# Latch - Solidity Verifier Generator
# =============================================================================
# Compiles the Noir circuit and generates a Solidity verifier contract.
# The verifier is used on-chain to verify ZK proofs of batch settlements.
#
# Usage: ./tools/generate-verifier.sh
# =============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

error() {
    echo -e "${RED}[✗]${NC} $1"
    exit 1
}

# Navigate to project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

CIRCUIT_DIR="circuits"
OUTPUT_DIR="src/verifier"

echo ""
echo "=============================================="
echo "  Latch Verifier Generator"
echo "=============================================="
echo ""

# Check prerequisites
if ! command -v nargo >/dev/null 2>&1; then
    error "nargo not found. Run ./tools/install-deps.sh first."
fi

if ! command -v bb >/dev/null 2>&1; then
    error "bb (barretenberg) not found. Run ./tools/install-deps.sh first."
fi

# -----------------------------------------------------------------------------
# Step 1: Compile Noir Circuit
# -----------------------------------------------------------------------------
info "Compiling Noir circuit..."

cd "$CIRCUIT_DIR"

if nargo compile; then
    success "Circuit compiled successfully"
else
    error "Circuit compilation failed"
fi

# -----------------------------------------------------------------------------
# Step 2: Generate Verification Key
# -----------------------------------------------------------------------------
info "Generating verification key..."

if bb write_vk -b ./target/batch_verifier.json -o ./target/vk; then
    success "Verification key generated"
else
    error "Failed to generate verification key"
fi

# -----------------------------------------------------------------------------
# Step 3: Generate Solidity Verifier
# -----------------------------------------------------------------------------
info "Generating Solidity verifier..."

cd "$PROJECT_ROOT"
mkdir -p "$OUTPUT_DIR"

VERIFIER_PATH="$OUTPUT_DIR/BatchVerifier.sol"

if bb write_solidity_verifier -b "$CIRCUIT_DIR/target/batch_verifier.json" -v "$CIRCUIT_DIR/target/vk" -o "$VERIFIER_PATH.tmp"; then
    success "Solidity verifier generated"
else
    error "Failed to generate Solidity verifier"
fi

# -----------------------------------------------------------------------------
# Step 4: Post-process Verifier
# -----------------------------------------------------------------------------
info "Post-processing verifier..."

# Add SPDX license identifier if not present
if ! grep -q "SPDX-License-Identifier" "$VERIFIER_PATH.tmp"; then
    {
        echo "// SPDX-License-Identifier: MIT"
        echo "// Generated by Barretenberg - DO NOT EDIT"
        echo ""
        cat "$VERIFIER_PATH.tmp"
    } > "$VERIFIER_PATH"
    rm "$VERIFIER_PATH.tmp"
else
    mv "$VERIFIER_PATH.tmp" "$VERIFIER_PATH"
fi

success "Verifier post-processed"

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------
echo ""
echo "=============================================="
echo -e "${GREEN}  Verifier Generated Successfully${NC}"
echo "=============================================="
echo ""
echo "Output files:"
echo "  - Verification key: $CIRCUIT_DIR/target/vk"
echo "  - Solidity verifier: $VERIFIER_PATH"
echo ""
echo "Next steps:"
echo "  1. Review the generated verifier contract"
echo "  2. Import it in your hook contract:"
echo "     import {UltraVerifier} from \"./verifier/BatchVerifier.sol\";"
echo ""
